# Generated by Django 3.2 on 2021-07-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMachine',
            fields=[
                ('MachineID', models.IntegerField(primary_key=True, serialize=False)),
                ('MachineName', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField()),
                ('logo', models.ImageField(upload_to='')),
                ('AssetID', models.CharField(max_length=100)),
            ],
        ),
    ]
